item {
  name: "Speed limit (20km/h)"
  id: 1
}
item {
  name: "Speed limit (30km/h)"
  id: 2
}
item {
  name: "Speed limit (50km/h)"
  id: 3
}
item {
  name: "Speed limit (60km/h)"
  id: 4
}
item {
  name: "Speed limit (70km/h)"
  id: 5
}
item {
  name: "Speed limit (80km/h)"
  id: 6
}
item {
  name: "End of speed limit (80km/h)"
  id: 7
}
item {
  name: "Speed limit (100km/h)"
  id: 8
}
item {
  name: "Speed limit (120km/h)"
  id: 9
}
item {
  name: "No passing"
  id: 10
}
item {
  name: "No passing veh over 3.5 tons"
  id: 11
}
item {
  name: "Right-of-way at intersection"
  id: 12
}
item {
  name: "Priority road"
  id: 13
}
item {
  name: "Yield"
  id: 14
}
item {
  name: "Stop"
  id: 15
}
item {
  name: "No vehicles"
  id: 16
}
item {
  name: "Veh > 3.5 tons prohibited"
  id: 17
}
item {
  name: "No entry"
  id: 18
}
item {
  name: "General caution"
  id: 19
}
item {
  name: "Dangerous curve left"
  id: 20
}
item {
  name: "Dangerous curve right"
  id: 21
}
item {
  name: "Double curve"
  id: 22
}
item {
  name: "Bumpy road"
  id: 23
}
item {
  name: "Slippery road"
  id: 24
}
item {
  name: "Road narrows on the right"
  id: 25
}
item {
  name: "Road work"
  id: 26
}
item {
  name: "Traffic signals"
  id: 27
}
item {
  name: "Pedestrians"
  id: 28
}
item {
  name: "Children crossing"
  id: 29
}
item {
  name: "Bicycles crossing"
  id: 30
}
item {
  name: "Beware of ice/snow"
  id: 31
}
item {
  name: "Wild animals crossing"
  id: 32
}
item {
  name: "End speed + passing limits"
  id: 33
}
item {
  name: "Turn right ahead"
  id: 34
}
item {
  name: "Turn left ahead"
  id: 35
}
item {
  name: "Ahead only"
  id: 36
}
item {
  name: "Go straight or right"
  id: 37
}
item {
  name: "Go straight or left"
  id: 38
}
item {
  name: "Keep right"
  id: 39
}
item {
  name: "Keep left"
  id: 40
}
item {
  name: "Roundabout mandatory"
  id: 41
}
item {
  name: "End of no passing"
  id: 42
}
item {
  name: "End no passing veh > 3.5 tons"
  id: 43
}
