item {
  name: "Speed limit (50km/h)"
  id: 1
}
item {
  name: "No vehicles"
  id: 2
}
item {
  name: "Veh > 3.5 tons prohibited"
  id: 3
}
item {
  name: "No entry"
  id: 4
}
item {
  name: "Turn right ahead"
  id: 5
}
item {
  name: "Turn left ahead"
  id: 6
}
item {
  name: "Ahead only"
  id: 7
}
item {
  name: "Go straight or right"
  id: 8
}
item {
  name: "Go straight or left"
  id: 9
}
item {
  name: "Speed limit (90km/h)"
  id: 10
}
